pipeline {
    agent {
        docker { image 'python:3.9-slim' }
    }
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'python3 -m pip install --no-cache-dir -r minimal_jenkins/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest --junitxml=results.xml'
            }
        }
        stage('Debug Environment') {
            steps {
                sh 'which python3'
                sh 'python3 --version'
                sh 'pip3 --version'
            }
        }
        stage('Publish Test Results') {
            steps {
                junit 'results.xml'
            }
        }
    }
    post {
        always {
            emailext (
                to: "dbaskak@gmail.com",
                subject: "Jenkins Pipeline Results: ${currentBuild.fullDisplayName}",
                body: """<p>Pipeline Result: ${currentBuild.result}</p>
                          <p>Details: ${env.BUILD_URL}</p>""",
                mimeType: 'text/html'
            )
        }
    }
}