pipeline {
    agent any
    environment {
        VENV_DIR = 'venv'
        PYTHONPATH = "${WORKSPACE}/docker_project:${WORKSPACE}/docker_project/app"
    }
    stages {
        stage('Checkout Code') {
            steps {
                echo 'Cloning repository for branch homework_31...'
                checkout scm: [
                    $class: 'GitSCM',
                    branches: [[name: '*/homework_31']],
                    userRemoteConfigs: [[url: 'https://github.com/dbaskak/aqa_01.git']]
                ]
            }
        }
        stage('Setup Environment') {
            steps {
                echo 'Setting up Python environment...'
                dir('docker_project') {
                    sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                    '''
                }
            }
